
/* 
import type { Metadata } from "next";

import "../public/assets/css/styles.css";
import Header  from "./_layout/header/Header";
import Footer from "./_layout/footer/footer";
import { WishlistProvider } from "./_context/WishlistContext";
import MobileHeader from "./_layout/header/MobileHeader";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Providers } from "./_context/Provider";
import { ToastContainer } from "react-toastify";



import { useContext } from 'react';
import { GlobalContext } from '@/app/_context/GlobalContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: 1,
      refetchOnWindowFocus: false,
    },
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const { drawerOpen,toggleDrawer, closeDrawer  } = useContext(GlobalContext);
  
  return (
    <html lang="en">
      <body  className="mobile-me4nu-active" > 
        <div className="body-overlay-1"></div>
        <ToastContainer />
        <Providers>
          <Header />
          <MobileHeader />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>

  );
}
 */



import type { Metadata } from "next";
import ClientLayout from "./client-layout";
import { Providers } from "./_context/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <Providers>
        <ClientLayout>{children}</ClientLayout>
      </Providers>
  );
}
